common: &common
  adapter: postgresql
  username: postgresql
  password:

development:
  <<: *common
  database: nitch_development

test:
  <<: *common
  database: nitch_test

production:
  <<: *common
  database: nitch_production

staging:
  <<: *common
  database: nitch_production
